version: '3'

services:
  db:
    image: mysql:8.0
    container_name: webchat
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=webchat
      - MYSQL_PASSWORD=webchat
      - MYSQL_DATABASE=webchat
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"