server:
  port: 8080

spring:
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format-sql: true